---
title: "mp3: final"
output: html_document
---
QUESTIONS FOR WEDNESDAY:

Make sure buffers are right size
Remote Campsite location???
Forest Aggregation

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(macleish)
library(tidyverse)
library(sf)
library(leaflet)
library(units)
```

```{r}
trails<-macleish_layers[["trails"]]
boundary<-macleish_layers[["boundary"]]

streams<-macleish_layers[["streams"]]
wetlands<-macleish_layers[["wetlands"]]

forests<-macleish_layers[["forests"]]

research<-macleish_layers[["research"]]
buildings<-macleish_layers[["buildings"]]

landmarks<-macleish_layers[["landmarks"]]
challengecourses<-macleish_layers[["challenge_courses"]]


```

```{r}
proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=42.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

point_to_sf <- function(lat, lon) {
  st_point(c(lat,lon)) %>%
    st_sfc(crs = 4326)
}

parking <- point_to_sf(-72.680663, 42.448013) %>%
  st_transform(crs = proj4_aea)
group_campsite <- point_to_sf(-72.678154, 42.450976)
remote_campsite <- point_to_sf(-72.674732, 42.458570)

# put 1/2 mi (804.672 m) buffer around parking area
parking_buffer <- st_buffer(parking, dist = 402.336) %>%
  st_transform(crs = 4326)

streams_inside <- boundary %>%
  st_intersection(streams)

parkbuffer<-parking%>%
  st_transform(proj4_aea)%>%
  st_buffer(dist= 402.336)%>%
  st_transform(4326)
  
streams_buffer <- streams_inside %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 30.48) %>%
  st_transform(4326)

ccbuffer<-challengecourses%>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 68.58) %>%
  st_transform(4326)

researchbuffer<-research%>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 68.58) %>%
  st_transform(4326)

wetlandbuffer<-wetlands%>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 68.58) %>%
  st_transform(4326)
```

```{r}
library(macleish)

bechtel <- data.frame(lat = 42.449167, lon = -72.679389)

aggforests<-forests%>%
  group_by(Sheet1__Na)%>%
  summarise(n=n())

forestpalette<-colorFactor(palette = "viridis",
                    domain = aggforests$Sheet1__Na)

library(RColorBrewer)
bechtel <- data.frame(lat = 42.449167, lon = -72.679389)

pale <- colorNumeric(palette = "inferno",
                    domain = contours$ELEV_M)
library(leaflet)
leaflet() %>%
  addTiles %>%
  addPolygons(data = boundary, weight = 1, fillOpacity = 0.1)%>%
  addMarkers(data = st_transform(parking, crs = 4326), popup = "Parking") %>%
  addMarkers(data = group_campsite, popup = "Group Campsite")%>%
  addMarkers(data = remote_campsite, popup = "Remote Campsite") %>%
addPolygons(data = parking_buffer, color = "green") %>%
  addPolygons(data = buildings, weight = 1, opacity = 1)%>%
  addPolygons(data = parking_buffer, color = "green") %>%
  addPolylines(data = streams_buffer, fillOpacity = 0.5) %>%
  addPolygons(data = buildings, weight = 1, opacity = 1) %>%
  addPolygons(data = parking_buffer, color = "red") %>%
  addPolylines(data = streams_buffer, fillOpacity = 0.5, color="green")%>%
 addPolygons(data = researchbuffer,fillOpacity = 0, weight=.5)%>%
  addPolygons(data=ccbuffer, fillOpacity = 0, weight=.5)%>%
  addPolygons(data=wetlands)%>%
  addMarkers(data=challengecourses)%>%
  addPolygons(data=research)%>%
  addMarkers(lng = ~lon, lat = ~lat, data = bechtel,
             popup = "Bechtel Environmental Classroom") %>%
  addPolygons(data = contours, color = ~pale(ELEV_M), weight = 0.5) %>%
  addPolygons(data=wetlandbuffer, color="green")
  addLegend("bottomright", pal = pale, values = contours$ELEV_M)

```