---
title: "mp3"
output: html_document
---

Group Campsite (42.450976, -72.678154)
Remote Campite (42.458570, -72.674732)
Parking (42.448013, -72.680663)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(macleish)
library(tidyverse)
library(sf)
library(leaflet)
library(data.table)
```

```{r}
trails<-macleish_layers[["trails"]]
boundary<-macleish_layers[["boundary"]]

streams<-macleish_layers[["streams"]]
wetlands<-macleish_layers[["wetlands"]]

forests<-macleish_layers[["forests"]]

research<-macleish_layers[["research"]]
buildings<-macleish_layers[["buildings"]]

landmarks<-macleish_layers[["landmarks"]]
challengecourses<-macleish_layers[["challenge_courses"]]
```

```{r, eval=FALSE}
url <- "http://wsgw.mass.gov/data/gispub/shape/state/contours250k.zip"
local_file <- basename(url)
download.file(url, destfile = local_file)
unzip(local_file, exdir = "contour")
```

```{r}
dsn <- path.expand("contour")
dsn
list.files(dsn)
contour_layer <- read_sf(dsn)
st_layers(dsn)

contour_layer <- st_transform(contour_layer, crs = 4326)

boundelev <- boundary %>%
  st_intersection(contour_layer)

boundelev%>%
  plot()

macleish_layers[["boundary"]]

boundelev %>%
  arrange(CONTOUR_FT)

proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=42.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

point_to_sf <- function(lat, lon) {
  st_point(c(lat,lon)) %>%
    st_sfc(crs = 4326)
}

parking <- point_to_sf(-72.680663, 42.448013) %>%
  st_transform(crs = proj4_aea)
group_campsite <- point_to_sf(-72.678154, 42.450976)
remote_campsite <- point_to_sf(-72.674732, 42.458570)

# put 1/2 mi (804.672 m) buffer around parking area
parking_buffer <- st_buffer(parking, dist = 402.336) %>%
  st_transform(crs = 4326)
streams_inside <- boundary %>%
  st_intersection(streams)
  
streams_buffer <- streams_inside %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = set_units(100, m)) %>%
  st_transform(4326)
```

```{r}
pal <- colorNumeric(palette = "inferno",
                    domain = boundelev[["CONTOUR_FT"]])
leaflet() %>%
  addTiles %>%
  addPolygons(data = boundary, weight = 1, fillOpacity = 0.1) %>%
  addMarkers(data = st_transform(parking, crs = 4326), popup = "Parking") %>%
  addMarkers(data = group_campsite, popup = "Group Campsite") %>%
  addMarkers(data = remote_campsite, popup = "Remote Campsite") %>%
  addPolygons(data = parking_buffer, color = "green") %>%
  addPolylines(data = streams_buffer, fillOpacity = 0.5)

plot(contour_layer)
            #, pal = pal, values = ~CONTOUR_FT,
    #title = "Contour Elevation",
    #opacity = 1)

```


1/2 mile from parking area

within 200` of a stream/water source

in a forest unlike the forest the other 2 are in

relatively flat

at least 500` from any research area or challenge course

Group Campsite (42.450976, -72.678154)
Remote Campite (42.458570, -72.674732)
Parking (42.448013, -72.680663)


```{r}
leaflet() %>%
  addTiles %>%
  addPolygons(data = boundary, weight = 1, fillOpacity = 0.1) %>%
  addMarkers(data = st_transform(parking, crs = 4326), popup = "Parking") %>%
  addMarkers(data = group_campsite, popup = "Group Campsite") %>%
  addMarkers(data = remote_campsite, popup = "Remote Campsite")%>%
  addPolylines(data=streams, weight=1)%>%
  addPolygons(data=wetlands, fillOpacity = 0.5)%>%
  addPolygons(data=aggforests, fillOpacity = .1)
```

```{r}
aggforests<-forests%>%
  group_by(Sheet1__Na)
```


